development:
  adapter: postgresql
  encoding: unicode
  database: redisco_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: redisco_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: redisco_production
  pool: 5
